# Generated by Django 5.1.6 on 2025-02-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('humidity', models.FloatField()),
                ('cloud_coverage', models.FloatField()),
                ('rain', models.FloatField(default=0)),
            ],
        ),
    ]
